package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ActorVisitor.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public interface ActorVisitor {
    void VisitStudent(Student s);
    
    void VisitTeacher(Teacher t);
}
