package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BeerMug.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class BeerMug extends LivingItem {
	@Override
	public void TimePassed() {

	}
}
