package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Charge.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public interface Charge {
    LivingItem creator = null;
    int GetPriority();
    void Affect();
}
