package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CSE.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class CSE extends LivingItem {
	@Override
	public void TimePassed() {

	}

	@Override
	public void Use() {

	}
}
