package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Curse.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class Curse implements RoomEffect {
	@Override
	public void TimePassed() {

	}

	@Override
	public void SetLocation(Room r) {

	}
}
