package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Door.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class Door implements Entity {
    private boolean hidden;
    private Room directedTowards;
    public void Hide() {
    }
    
    public void Show() {
    }
    
    public boolean GoThrough(Room r, Actor a) {
    }
    
    public void SetRooms(Room r1, Room r2) {
    }
    
    public Room[2] GetRooms() {
    }
    
    public void ChangeRoom(Room r1, Room r2) {
    }

    @Override
    public void TimePassed() {

    }
}
