package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DropOutProtection.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class DropOutProtection implements Charge {
}
