package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entity.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//


public interface Entity {
    void TimePassed();
}
