package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GasPoisoning.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class GasPoisoning implements RoomEffect {
    private int lifetime;
}
