package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//


import lab.proj.model.Entity;

public abstract class Item implements Entity {
    private boolean activated;
    private boolean dead;
    private Actor actor;
    public boolean PickUp(Actor a) {
    }
    
    public void Drop() {
    }
    
    public boolean IsPickedUp() {
    }
    
    public void Activate() {
    }
    
    public boolean IsActivated() {
    }
    
    public void ApplyCharges() {
    }
}
