package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LivingItem.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//


public abstract class LivingItem extends Item {
    private int lifetime;
    public abstract void Use();
}
