package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RoomEffect.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public interface RoomEffect extends Entity {
    void SetLocation(Room r);
}
