package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Room.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//


import lab.proj.model.Entity;

import java.util.List;

public class Room implements Entity {
    private int capacity;
    private List<Actor> actorsInside;
    private List<Item> itemsOnTheFloor;
    private List<RoomEffect> activeEffects;
    public boolean StepIn(Actor a) {
    }
    
    public void StepOut(Actor a) {
    }
    
    public List<Door> GetDoors() {
    }
    
    public List<Item> GetItems() {
        return itemsOnTheFloor;
    }
    
    public void AddItem(Item i) {
        itemsOnTheFloor.add(i);
    }
    
    public void RemoveItem(Item i) {
        itemsOnTheFloor.remove(i);
    }
    
    public void Merge() {
    }
    
    public void Split() {
    }
    
    public void AddEffect(RoomEffect e) {
        activeEffects.add(e);
    }
    
    public void RemoveEffect(RoomEffect e) {
        activeEffects.remove(e);
    }
    
    public void VisitActors(ActorVisitor v) {
    }
    
    public void AddDoor(Door d) {
    }
    
    public void RemoveDoor(Door d) {
    }
    
    public List<Actor> GetActors() {
        return actorsInside;
    }
    
    public int GetCapacity() {
        return capacity;
    }
    
    public void SetCapacity(int i) {
        capacity = i;
    }
    
    public List<RoomEffect> GetEffects() {
        return activeEffects;
    }

    @Override
    public void TimePassed() {

    }
}
