package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class Student extends Actor {
    private boolean droppedOut;
    private Charge gasProtections;
    private Charge dropOutProtections;
    public void DropOut() {
    }
    
    public void AddCharge(Charge c) {
    }
    
    public void RemoveCharge(Charge c) {
    }
    
    public boolean IsBlocked() {
    }
    
    public boolean IsDroppedOut() {
    }

    @Override
    public void TimePassed() {

    }
}
