package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teacher.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class Teacher extends Actor {
    public void Stun() {
    }
    
    public void DropOutStudent(Student s) {
    }
    
    public void DropOutAll() {
    }

    @Override
    public void TimePassed() {

    }
}
