package lab.proj.model;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transistor.java
//  @ Date : 2024. 03. 21.
//  @ Author : 
//
//




public class Transistor extends Item {
    private Room location;
    private Transistor pair;
    public void Drop() {
    }
    
    public void PairWith(Transistor t) {
    }
}
